### ISSUE TITLE
nerdctl panics on missing XDG_RUNTIME_DIR env var

### ISSUE THREAD

**Issue by 06kellyjac** [AkihiroSuda/nerdctl#110]
Expected behavior: I'd expect it to exit more cleanly where XDG_RUNTIME_DIR is really needed & continue on where it isn't needed

```bash
$ nerdctl completion bash

panic: environment variable XDG_RUNTIME_DIR is not set

goroutine 1 [running]:
github.com/AkihiroSuda/nerdctl/pkg/defaults.BuildKitHost(0x203000, 0x203000)
        github.com/AkihiroSuda/nerdctl/pkg/defaults/defaults.go:86 +0x105
main.init()
        github.com/AkihiroSuda/nerdctl/build.go:42 +0x34
```

**Comment by AkihiroSuda** [comment]
Fixed in https://github.com/AkihiroSuda/nerdctl/pull/111
